## Exercici 5

* Gestión de errores con async/await: Modifica la función del ejercicio 4 para que capture cualquier posible error utilizando un bloque try/catch.

### solucion propuesta